// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfTiptiW_zgKr4ZjmVXLsJ7AXW1MKqX3M',
    appId: '1:488881301243:web:43f6d7d5f2e990465eb25e',
    messagingSenderId: '488881301243',
    projectId: 'futureyou-4124d',
    authDomain: 'futureyou-4124d.firebaseapp.com',
    storageBucket: 'futureyou-4124d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrrME9F0ns0ZiiIa1WU919dcUgkmhkQvA',
    appId: '1:488881301243:android:0182dddd74bc82bd5eb25e',
    messagingSenderId: '488881301243',
    projectId: 'futureyou-4124d',
    storageBucket: 'futureyou-4124d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIn8Cit17_PEvVEFCGO6uTtDdsgHj6i_w',
    appId: '1:488881301243:ios:4958e2c2a4ac15055eb25e',
    messagingSenderId: '488881301243',
    projectId: 'futureyou-4124d',
    storageBucket: 'futureyou-4124d.firebasestorage.app',
    iosBundleId: 'com.example.futureYou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIn8Cit17_PEvVEFCGO6uTtDdsgHj6i_w',
    appId: '1:488881301243:ios:4958e2c2a4ac15055eb25e',
    messagingSenderId: '488881301243',
    projectId: 'futureyou-4124d',
    storageBucket: 'futureyou-4124d.firebasestorage.app',
    iosBundleId: 'com.example.futureYou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfTiptiW_zgKr4ZjmVXLsJ7AXW1MKqX3M',
    appId: '1:488881301243:web:d45aafc68a836cc55eb25e',
    messagingSenderId: '488881301243',
    projectId: 'futureyou-4124d',
    authDomain: 'futureyou-4124d.firebaseapp.com',
    storageBucket: 'futureyou-4124d.firebasestorage.app',
  );
}
